#include "pathkit/pathops/SkPathOpsAsWinding.cpp"
#include "pathkit/pathops/SkPathOpsCommon.cpp"
#include "pathkit/pathops/SkPathOpsConic.cpp"
#include "pathkit/pathops/SkPathOpsCubic.cpp"
#include "pathkit/pathops/SkPathOpsCurve.cpp"
#include "pathkit/pathops/SkPathOpsLine.cpp"
#include "pathkit/pathops/SkPathOpsOp.cpp"
#include "pathkit/pathops/SkPathOpsQuad.cpp"
#include "pathkit/pathops/SkPathOpsRect.cpp"
#include "pathkit/pathops/SkPathOpsSimplify.cpp"
#include "pathkit/pathops/SkPathOpsTSect.cpp"
#include "pathkit/pathops/SkPathOpsTightBounds.cpp"
#include "pathkit/pathops/SkPathOpsTypes.cpp"
#include "pathkit/pathops/SkPathOpsWinding.cpp"

#include "pathkit/pathops/SkPathOpsDebug.cpp"