#include "src/pathops/SkPathOpsAsWinding.cpp"
#include "src/pathops/SkPathOpsCommon.cpp"
#include "src/pathops/SkPathOpsConic.cpp"
#include "src/pathops/SkPathOpsCubic.cpp"
#include "src/pathops/SkPathOpsCurve.cpp"
#include "src/pathops/SkPathOpsLine.cpp"
#include "src/pathops/SkPathOpsOp.cpp"
#include "src/pathops/SkPathOpsQuad.cpp"
#include "src/pathops/SkPathOpsRect.cpp"
#include "src/pathops/SkPathOpsSimplify.cpp"
#include "src/pathops/SkPathOpsTSect.cpp"
#include "src/pathops/SkPathOpsTightBounds.cpp"
#include "src/pathops/SkPathOpsTypes.cpp"
#include "src/pathops/SkPathOpsWinding.cpp"

#include "src/pathops/SkPathOpsDebug.cpp"